# mysql -u root -p
# CREATE USER 'industry_mapping'@127.0.0.1 IDENTIFIED BY 'industry_mapping';
# GRANT ALL PRIVILEGES ON industry_mapping_test.* TO 'industry_mapping'@127.0.0.1;
# GRANT ALL PRIVILEGES ON industry_mapping_development.* TO 'industry_mapping'@127.0.0.1;

development: &default
  adapter: mysql2
  encoding: utf8
  database: industry_mapping_development
  pool: 5
  host: 127.0.0.1
  username: industry_mapping
  password: industry_mapping
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: industry_mapping_test
